from app.db.engine import create_engine_from_url
from app.db.models import Base

MIGRATION_NAMES = [
    "001_add_feature_elo_columns",
    "002_add_identity_unique_indexes",
    "003_create_live_runs",
    "004_create_ai_analysis_runs",
    "005_create_paper_recommendations",
]


def init_db(database_url: str) -> None:
    engine = create_engine_from_url(database_url)
    try:
        Base.metadata.create_all(engine)
        run_migrations(engine)
    finally:
        engine.dispose()


def run_migrations(engine) -> None:
    with engine.begin() as connection:
        _create_schema_migrations(connection)
        if connection.dialect.name != "sqlite":
            _record_noop_migrations_for_model_managed_database(connection)
            return
        _run_migration(
            connection,
            "001_add_feature_elo_columns",
            _add_feature_elo_columns,
        )
        _run_migration(
            connection,
            "002_add_identity_unique_indexes",
            _add_identity_unique_indexes,
        )
        _run_migration(
            connection,
            "003_create_live_runs",
            _create_live_runs,
        )
        _run_migration(
            connection,
            "004_create_ai_analysis_runs",
            _create_ai_analysis_runs,
        )
        _run_migration(
            connection,
            "005_create_paper_recommendations",
            _create_paper_recommendations,
        )


def _run_migration(connection, migration_name: str, migration) -> None:
    already_applied = connection.exec_driver_sql(
        "SELECT 1 FROM schema_migrations WHERE migration_name = ?",
        (migration_name,),
    ).fetchone()
    if already_applied:
        return

    migration(connection)
    connection.exec_driver_sql(
        """
        INSERT INTO schema_migrations (migration_name, applied_at)
        VALUES (?, datetime('now'))
        """,
        (migration_name,),
    )


def _create_schema_migrations(connection) -> None:
    if connection.dialect.name == "sqlite":
        connection.exec_driver_sql(
            """
            CREATE TABLE IF NOT EXISTS schema_migrations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                migration_name TEXT NOT NULL UNIQUE,
                applied_at TEXT NOT NULL
            )
            """
        )
        return

    connection.exec_driver_sql(
        """
        CREATE TABLE IF NOT EXISTS schema_migrations (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            migration_name TEXT NOT NULL UNIQUE,
            applied_at TEXT NOT NULL
        )
        """
    )


def _record_noop_migrations_for_model_managed_database(connection) -> None:
    for migration_name in MIGRATION_NAMES:
        connection.exec_driver_sql(
            """
            INSERT INTO schema_migrations (migration_name, applied_at)
            VALUES (%(migration_name)s, CURRENT_TIMESTAMP)
            ON CONFLICT (migration_name) DO NOTHING
            """,
            {"migration_name": migration_name},
        )


def _add_feature_elo_columns(connection) -> None:
    table_names = {
        row[0]
        for row in connection.exec_driver_sql(
            "SELECT name FROM sqlite_master WHERE type = 'table'"
        ).fetchall()
    }
    if "features" not in table_names:
        return

    column_names = {
        row[1] for row in connection.exec_driver_sql("PRAGMA table_info(features)").fetchall()
    }
    if "home_elo_rating" not in column_names:
        connection.exec_driver_sql("ALTER TABLE features ADD COLUMN home_elo_rating REAL")
    if "away_elo_rating" not in column_names:
        connection.exec_driver_sql("ALTER TABLE features ADD COLUMN away_elo_rating REAL")


def _add_identity_unique_indexes(connection) -> None:
    table_names = {
        row[0]
        for row in connection.exec_driver_sql(
            "SELECT name FROM sqlite_master WHERE type = 'table'"
        ).fetchall()
    }

    if "odds_snapshots" in table_names:
        connection.exec_driver_sql(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS uq_odds_snapshot_identity
            ON odds_snapshots (
                match_id,
                source,
                bookmaker,
                market,
                selection,
                snapshot_time
            )
            """
        )

    if "paper_bets" in table_names:
        connection.exec_driver_sql(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS uq_paper_bets_prediction_id
            ON paper_bets (prediction_id)
            """
        )


def _create_live_runs(connection) -> None:
    connection.exec_driver_sql(
        """
        CREATE TABLE IF NOT EXISTS live_runs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            run_id TEXT NOT NULL,
            run_type TEXT NOT NULL,
            provider TEXT NOT NULL,
            league TEXT,
            season TEXT,
            status TEXT NOT NULL,
            started_at TEXT NOT NULL,
            finished_at TEXT,
            items_read INTEGER NOT NULL DEFAULT 0,
            items_created INTEGER NOT NULL DEFAULT 0,
            items_updated INTEGER NOT NULL DEFAULT 0,
            items_skipped INTEGER NOT NULL DEFAULT 0,
            errors_count INTEGER NOT NULL DEFAULT 0,
            error_summary TEXT,
            model_name TEXT,
            created_at TEXT NOT NULL
        )
        """
    )
    connection.exec_driver_sql(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_live_runs_run_id
        ON live_runs (run_id)
        """
    )
    connection.exec_driver_sql(
        """
        CREATE INDEX IF NOT EXISTS idx_live_runs_status
        ON live_runs (status)
        """
    )
    connection.exec_driver_sql(
        """
        CREATE INDEX IF NOT EXISTS idx_live_runs_started_at
        ON live_runs (started_at)
        """
    )
    connection.exec_driver_sql(
        """
        CREATE INDEX IF NOT EXISTS idx_live_runs_provider_type
        ON live_runs (provider, run_type)
        """
    )


def _create_ai_analysis_runs(connection) -> None:
    connection.exec_driver_sql(
        """
        CREATE TABLE IF NOT EXISTS ai_analysis_runs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            analysis_type TEXT NOT NULL,
            source_type TEXT NOT NULL,
            source_id TEXT,
            input_json TEXT NOT NULL,
            output_json TEXT NOT NULL,
            model_name TEXT NOT NULL,
            prompt_version TEXT NOT NULL,
            status TEXT NOT NULL,
            error_summary TEXT,
            created_at TEXT NOT NULL
        )
        """
    )
    connection.exec_driver_sql(
        """
        CREATE INDEX IF NOT EXISTS idx_ai_analysis_type_created
        ON ai_analysis_runs (analysis_type, created_at)
        """
    )
    connection.exec_driver_sql(
        """
        CREATE INDEX IF NOT EXISTS idx_ai_analysis_source
        ON ai_analysis_runs (source_type, source_id)
        """
    )
    connection.exec_driver_sql(
        """
        CREATE INDEX IF NOT EXISTS idx_ai_analysis_status
        ON ai_analysis_runs (status)
        """
    )


def _create_paper_recommendations(connection) -> None:
    connection.exec_driver_sql(
        """
        CREATE TABLE IF NOT EXISTS paper_recommendations (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            match_id INTEGER NOT NULL,
            prediction_id INTEGER,
            source_run_id TEXT,
            source_match_id TEXT NOT NULL,
            bookmaker TEXT NOT NULL,
            market TEXT NOT NULL,
            selection TEXT NOT NULL,
            latest_snapshot_time TEXT NOT NULL,
            model_name TEXT NOT NULL,
            model_version TEXT NOT NULL,
            grade TEXT NOT NULL,
            status TEXT NOT NULL,
            model_probability REAL,
            implied_probability REAL,
            edge REAL,
            confidence_score REAL,
            current_odds REAL,
            expected_value REAL,
            risk_flags_json TEXT NOT NULL,
            rationale TEXT NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY(match_id) REFERENCES matches(id),
            FOREIGN KEY(prediction_id) REFERENCES predictions(id)
        )
        """
    )
    connection.exec_driver_sql(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_paper_recommendation_identity
        ON paper_recommendations (
            source_match_id,
            market,
            selection,
            model_name,
            model_version,
            latest_snapshot_time
        )
        """
    )
    connection.exec_driver_sql(
        """
        CREATE INDEX IF NOT EXISTS idx_paper_recommendations_grade
        ON paper_recommendations (grade)
        """
    )
    connection.exec_driver_sql(
        """
        CREATE INDEX IF NOT EXISTS idx_paper_recommendations_created
        ON paper_recommendations (created_at)
        """
    )
