import sqlite3

import pytest
from sqlalchemy.exc import IntegrityError

from app.db.engine import create_engine_from_url, session_scope
from app.db.migrations import (
    _create_schema_migrations,
    _record_noop_migrations_for_model_managed_database,
    init_db,
)
from app.db.models import AIAnalysisRun, Base, DecisionLog, LiveRun, OddsSnapshot
from app.db.repositories import (
    DecisionLogRepository,
    LiveRunRepository,
    MatchRepository,
    OddsSnapshotRepository,
)


def test_init_db_creates_expected_tables(tmp_path) -> None:
    db_path = tmp_path / "paper_odds_lab.sqlite"
    database_url = f"sqlite:///{db_path.as_posix()}"

    init_db(database_url)

    assert db_path.exists()
    with sqlite3.connect(db_path) as connection:
        table_names = {
            row[0]
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name"
            )
        }

    assert {
        "decision_logs",
        "evaluation_runs",
        "ai_analysis_runs",
        "features",
        "matches",
        "live_runs",
        "odds_snapshots",
        "paper_recommendations",
        "paper_bets",
        "predictions",
        "schema_migrations",
    }.issubset(table_names)


def test_postgres_schema_migration_table_uses_identity_column() -> None:
    connection = FakeConnection("postgresql")

    _create_schema_migrations(connection)

    assert "GENERATED BY DEFAULT AS IDENTITY" in connection.statements[0][0]
    assert "AUTOINCREMENT" not in connection.statements[0][0]


def test_postgres_model_managed_migrations_are_recorded_as_noops() -> None:
    connection = FakeConnection("postgresql")

    _record_noop_migrations_for_model_managed_database(connection)

    assert len(connection.statements) == 5
    assert all("ON CONFLICT" in statement for statement, _params in connection.statements)
    assert connection.statements[0][1] == {"migration_name": "001_add_feature_elo_columns"}


def test_init_db_upgrades_old_database_with_missing_elo_feature_columns(tmp_path) -> None:
    db_path = tmp_path / "old.sqlite"
    database_url = f"sqlite:///{db_path.as_posix()}"

    with sqlite3.connect(db_path) as connection:
        connection.execute(
            """
            CREATE TABLE features (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                match_id INTEGER NOT NULL,
                market TEXT NOT NULL,
                selection TEXT NOT NULL,
                home_form_points_5 REAL,
                away_form_points_5 REAL,
                home_goals_for_avg_5 REAL,
                away_goals_for_avg_5 REAL,
                home_goals_against_avg_5 REAL,
                away_goals_against_avg_5 REAL,
                home_advantage_flag INTEGER,
                bookmaker_probability REAL,
                bookmaker_margin_estimate REAL,
                feature_version TEXT NOT NULL,
                created_at TEXT NOT NULL
            )
            """
        )

    init_db(database_url)
    init_db(database_url)

    with sqlite3.connect(db_path) as connection:
        feature_columns = {
            row[1] for row in connection.execute("PRAGMA table_info(features)").fetchall()
        }
        migration_rows = connection.execute(
            "SELECT migration_name FROM schema_migrations"
        ).fetchall()

    assert "home_elo_rating" in feature_columns
    assert "away_elo_rating" in feature_columns
    assert migration_rows == [
        ("001_add_feature_elo_columns",),
        ("002_add_identity_unique_indexes",),
        ("003_create_live_runs",),
        ("004_create_ai_analysis_runs",),
        ("005_create_paper_recommendations",),
    ]


def test_init_db_upgrades_old_database_with_identity_uniqueness_indexes(tmp_path) -> None:
    db_path = tmp_path / "old-identity.sqlite"
    database_url = f"sqlite:///{db_path.as_posix()}"

    with sqlite3.connect(db_path) as connection:
        connection.executescript(
            """
            CREATE TABLE matches (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                source TEXT NOT NULL,
                source_match_id TEXT NOT NULL,
                league TEXT NOT NULL,
                home_team TEXT NOT NULL,
                away_team TEXT NOT NULL,
                kickoff_time TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'scheduled',
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );
            CREATE TABLE predictions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                match_id INTEGER NOT NULL,
                market TEXT NOT NULL,
                selection TEXT NOT NULL,
                model_name TEXT NOT NULL,
                model_version TEXT NOT NULL,
                model_probability REAL NOT NULL,
                bookmaker_probability REAL NOT NULL,
                edge REAL NOT NULL,
                decision TEXT NOT NULL,
                created_at TEXT NOT NULL
            );
            CREATE TABLE odds_snapshots (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                match_id INTEGER NOT NULL,
                source TEXT NOT NULL,
                bookmaker TEXT NOT NULL,
                market TEXT NOT NULL,
                selection TEXT NOT NULL,
                odds_decimal REAL NOT NULL,
                implied_probability REAL NOT NULL,
                snapshot_time TEXT NOT NULL,
                minutes_before_kickoff INTEGER,
                is_closing BOOLEAN NOT NULL DEFAULT 0,
                created_at TEXT NOT NULL
            );
            CREATE TABLE paper_bets (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                prediction_id INTEGER NOT NULL,
                match_id INTEGER NOT NULL,
                market TEXT NOT NULL,
                selection TEXT NOT NULL,
                odds_taken REAL NOT NULL,
                stake_units REAL NOT NULL,
                expected_value REAL NOT NULL,
                status TEXT NOT NULL DEFAULT 'open',
                created_at TEXT NOT NULL
            );
            """
        )

    init_db(database_url)
    init_db(database_url)

    with sqlite3.connect(db_path) as connection:
        odds_indexes = {
            row[1] for row in connection.execute("PRAGMA index_list(odds_snapshots)")
        }
        paper_bet_indexes = {
            row[1] for row in connection.execute("PRAGMA index_list(paper_bets)")
        }
        migration_rows = connection.execute(
            "SELECT migration_name FROM schema_migrations ORDER BY migration_name"
        ).fetchall()

    assert "uq_odds_snapshot_identity" in odds_indexes
    assert "uq_paper_bets_prediction_id" in paper_bet_indexes
    assert migration_rows == [
        ("001_add_feature_elo_columns",),
        ("002_add_identity_unique_indexes",),
        ("003_create_live_runs",),
        ("004_create_ai_analysis_runs",),
        ("005_create_paper_recommendations",),
    ]


def test_init_db_upgrades_old_database_with_live_run_registry(tmp_path) -> None:
    db_path = tmp_path / "old-live-runs.sqlite"
    database_url = f"sqlite:///{db_path.as_posix()}"

    with sqlite3.connect(db_path) as connection:
        connection.execute(
            """
            CREATE TABLE matches (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                source TEXT NOT NULL,
                source_match_id TEXT NOT NULL,
                league TEXT NOT NULL,
                home_team TEXT NOT NULL,
                away_team TEXT NOT NULL,
                kickoff_time TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'scheduled',
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """
        )

    init_db(database_url)
    init_db(database_url)

    with sqlite3.connect(db_path) as connection:
        table_names = {
            row[0]
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type='table'"
            )
        }
        live_run_columns = {
            row[1] for row in connection.execute("PRAGMA table_info(live_runs)").fetchall()
        }
        live_run_indexes = {
            row[1] for row in connection.execute("PRAGMA index_list(live_runs)")
        }
        migration_rows = connection.execute(
            "SELECT migration_name FROM schema_migrations ORDER BY migration_name"
        ).fetchall()

    assert "live_runs" in table_names
    assert {
        "run_id",
        "run_type",
        "provider",
        "status",
        "items_read",
        "errors_count",
        "error_summary",
    }.issubset(live_run_columns)
    assert "uq_live_runs_run_id" in live_run_indexes
    assert migration_rows == [
        ("001_add_feature_elo_columns",),
        ("002_add_identity_unique_indexes",),
        ("003_create_live_runs",),
        ("004_create_ai_analysis_runs",),
        ("005_create_paper_recommendations",),
    ]


def test_init_db_upgrades_old_database_with_ai_analysis_runs(tmp_path) -> None:
    db_path = tmp_path / "old-ai-analysis.sqlite"
    database_url = f"sqlite:///{db_path.as_posix()}"

    with sqlite3.connect(db_path) as connection:
        connection.execute(
            """
            CREATE TABLE matches (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                source TEXT NOT NULL,
                source_match_id TEXT NOT NULL,
                league TEXT NOT NULL,
                home_team TEXT NOT NULL,
                away_team TEXT NOT NULL,
                kickoff_time TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'scheduled',
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """
        )

    init_db(database_url)
    init_db(database_url)

    with sqlite3.connect(db_path) as connection:
        table_names = {
            row[0]
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type='table'"
            )
        }
        column_names = {
            row[1]
            for row in connection.execute("PRAGMA table_info(ai_analysis_runs)").fetchall()
        }
        migration_rows = connection.execute(
            "SELECT migration_name FROM schema_migrations ORDER BY migration_name"
        ).fetchall()

    assert "ai_analysis_runs" in table_names
    assert {
        "analysis_type",
        "source_type",
        "input_json",
        "output_json",
        "model_name",
        "prompt_version",
        "status",
    }.issubset(column_names)
    assert migration_rows == [
        ("001_add_feature_elo_columns",),
        ("002_add_identity_unique_indexes",),
        ("003_create_live_runs",),
        ("004_create_ai_analysis_runs",),
        ("005_create_paper_recommendations",),
    ]


def test_match_repository_inserts_match_and_rejects_duplicate_source_id(tmp_path) -> None:
    engine = create_engine_from_url(f"sqlite:///{(tmp_path / 'test.sqlite').as_posix()}")
    Base.metadata.create_all(engine)

    with session_scope(engine) as session:
        repository = MatchRepository(session)
        repository.add(
            source="sample",
            source_match_id="match-001",
            league="Demo League",
            season="2026",
            home_team="North FC",
            away_team="South FC",
            kickoff_time="2026-05-19T18:00:00+00:00",
            raw_payload_json='{"id":"match-001"}',
        )

    with pytest.raises(IntegrityError):
        with session_scope(engine) as session:
            repository = MatchRepository(session)
            repository.add(
                source="sample",
                source_match_id="match-001",
                league="Demo League",
                season="2026",
                home_team="North FC",
                away_team="South FC",
                kickoff_time="2026-05-19T18:00:00+00:00",
            )


def test_odds_snapshot_repository_inserts_snapshot(tmp_path) -> None:
    engine = create_engine_from_url(f"sqlite:///{(tmp_path / 'test.sqlite').as_posix()}")
    Base.metadata.create_all(engine)

    with session_scope(engine) as session:
        match = MatchRepository(session).add(
            source="sample",
            source_match_id="match-001",
            league="Demo League",
            home_team="North FC",
            away_team="South FC",
            kickoff_time="2026-05-19T18:00:00+00:00",
        )
        snapshot = OddsSnapshotRepository(session).add(
            match_id=match.id,
            source="sample",
            bookmaker="DemoBook",
            market="1X2",
            selection="HOME",
            odds_decimal=2.1,
            implied_probability=1 / 2.1,
            snapshot_time="2026-05-18T18:00:00+00:00",
            minutes_before_kickoff=1440,
        )

    with session_scope(engine) as session:
        stored = session.get(OddsSnapshot, snapshot.id)

        assert stored is not None
        assert stored.bookmaker == "DemoBook"
        assert stored.market == "1X2"
        assert stored.selection == "HOME"
        assert stored.is_closing is False


def test_decision_log_repository_inserts_audit_log(tmp_path) -> None:
    engine = create_engine_from_url(f"sqlite:///{(tmp_path / 'test.sqlite').as_posix()}")
    Base.metadata.create_all(engine)

    with session_scope(engine) as session:
        log = DecisionLogRepository(session).add(
            stage="COLLECT_MATCHES",
            level="INFO",
            message="Imported sample match",
            input_json='{"source":"sample"}',
            output_json='{"created":1}',
        )

    with session_scope(engine) as session:
        stored = session.get(DecisionLog, log.id)

        assert stored is not None
        assert stored.stage == "COLLECT_MATCHES"
        assert stored.level == "INFO"
        assert stored.message == "Imported sample match"


def test_live_run_repository_starts_completes_and_reloads_run(tmp_path) -> None:
    db_path = tmp_path / "test.sqlite"
    engine = create_engine_from_url(f"sqlite:///{db_path.as_posix()}")
    Base.metadata.create_all(engine)

    with session_scope(engine) as session:
        run = LiveRunRepository(session).start(
            run_id="run-001",
            run_type="collect_odds",
            provider="misli_public",
            league="football",
            season="2026",
            model_name=None,
        )
        LiveRunRepository(session).complete(
            run_id=run.run_id,
            items_read=3,
            items_created=2,
            items_updated=1,
            items_skipped=0,
        )

    engine.dispose()
    reloaded_engine = create_engine_from_url(f"sqlite:///{db_path.as_posix()}")
    try:
        with session_scope(reloaded_engine) as session:
            stored = LiveRunRepository(session).get_by_run_id("run-001")

            assert stored is not None
            assert stored.status == "completed"
            assert stored.items_read == 3
            assert stored.items_created == 2
            assert stored.items_updated == 1
            assert stored.finished_at is not None
    finally:
        reloaded_engine.dispose()


def test_live_run_repository_fails_run_with_error_summary(tmp_path) -> None:
    engine = create_engine_from_url(f"sqlite:///{(tmp_path / 'test.sqlite').as_posix()}")
    Base.metadata.create_all(engine)

    with session_scope(engine) as session:
        repository = LiveRunRepository(session)
        repository.start(
            run_id="run-002",
            run_type="collect_matches",
            provider="misli_public",
        )
        failed = repository.fail(
            run_id="run-002",
            errors_count=2,
            error_summary="Missing full kickoff datetime",
            items_read=5,
            items_skipped=5,
        )

        assert failed.status == "failed"
        assert failed.errors_count == 2
        assert failed.error_summary == "Missing full kickoff datetime"
        assert failed.items_read == 5
        assert failed.items_skipped == 5
        assert failed.finished_at is not None


def test_live_run_repository_start_is_idempotent_for_same_run_id(tmp_path) -> None:
    engine = create_engine_from_url(f"sqlite:///{(tmp_path / 'test.sqlite').as_posix()}")
    Base.metadata.create_all(engine)

    with session_scope(engine) as session:
        repository = LiveRunRepository(session)
        first = repository.start(
            run_id="run-003",
            run_type="collect_matches",
            provider="misli_public",
        )
        second = repository.start(
            run_id="run-003",
            run_type="collect_matches",
            provider="misli_public",
        )

        assert first.id == second.id
        assert session.query(LiveRun).count() == 1


def test_ai_analysis_run_repository_inserts_advisory_record(tmp_path) -> None:
    engine = create_engine_from_url(f"sqlite:///{(tmp_path / 'test.sqlite').as_posix()}")
    Base.metadata.create_all(engine)

    with session_scope(engine) as session:
        analysis = AIAnalysisRun(
            analysis_type="live_status_summary",
            source_type="live_status",
            source_id="run-001",
            input_json='{"latest_run":"run-001"}',
            output_json='{"label":"AI-assisted advisory analysis"}',
            model_name="deterministic_ai_fallback",
            prompt_version="ai-live-status-v1",
            status="completed",
        )
        session.add(analysis)
        session.flush()

    with session_scope(engine) as session:
        stored = session.get(AIAnalysisRun, analysis.id)

    assert stored is not None
    assert stored.analysis_type == "live_status_summary"
    assert stored.model_name == "deterministic_ai_fallback"


class FakeDialect:
    def __init__(self, name: str) -> None:
        self.name = name


class FakeConnection:
    def __init__(self, dialect_name: str) -> None:
        self.dialect = FakeDialect(dialect_name)
        self.statements: list[tuple[str, object]] = []

    def exec_driver_sql(self, statement: str, parameters: object = None):
        self.statements.append((statement, parameters))
        return None
